# Generated by Django 2.2.16 on 2020-09-15 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200915_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='importante',
            field=models.CharField(choices=[('T', 'Sim'), ('F', 'Não')], default='Não', max_length=1),
        ),
    ]
